---
BOT_NAME: 'VredditDownloader'
USER_AGENT: 'REDDIT_USER_AGENT'
NO_FOOTER_SUBS: 
  - 'SUBREDDIT_TO_POST_WITHOUT_FOOTER'
  - 'ANOTHER_SUB'
PM_SUBS: 
  - 'SUBREDDIT_TO_SEND_PM_INSTEAD_OF_COMMENT'
  - 'ANOTHER_SUB'
BLACKLIST_SUBS:
  - 'SUB_TO_BLACKLIST'
  - 'ANOTHER_SUB'
BLACKLIST_USERS:
  - 'USER_TO_BLACKLIST'
  - 'ANOTHER_USER'
PM_SUBJECT: "I couldn't reply to your comment so you get a PM instead :)"
ANNOUNCEMENT_PM: "\n\nI also work with links sent by PM."
HEADER: "*beep. boop.* 🤖 I'm a bot that helps downloading videos!\n\n"
INFO_LINK: "[**Info**](https://np.reddit.com/user/VredditDownloader/comments/cju1dg/info/)"
DONATION_LINK: "[**Support&#32;me&#32;❤**](https://www.paypal.me/synapsensalat)"
GITHUB_LINK: "[**Github**](https://github.com/JohannesPertl/vreddit-downloader)"
INBOX_LIMIT: 20
REQUEST_AGE_LIMIT: 10
